# Generated by Django 5.0.2 on 2024-02-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgeory',
            new_name='category',
        ),
    ]
