# Generated by Django 5.0.2 on 2024-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders_commentproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
