# Generated by Django 5.0.2 on 2024-02-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orders_amount_orders_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='store.product'),
        ),
    ]
