# Generated by Django 5.0.2 on 2024-02-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_commentproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
